<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInit284383e793fdc93c0e4a37440a76b57a
{
    public static $files = array (
        '5e97df31a48c3d8473c36e3f1c45e0a4' => __DIR__ . '/..' . '/athlon1600/youtube-downloader/src/YouTubeDownloader.php',
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {

        }, null, ClassLoader::class);
    }
}
